### ISSUE TITLE
API changes for 0.9

### ISSUE THREAD

**Issue by nical** [nical/lyon#242]
Filing this as a reminder since I'd like to wait and batch all breaking API changes towards the end of the 0.8 cycle, so that we can keep publishing bug fixes in features in the 0.8 series.

- [x] remove `tessellate_flattened_path` (`tessellate_path` is strictly better),
- [x] simplify the crate structure (see #239),
- [x] pass `GeometryBuilder`s as trait objects (see #246)
- [x] (optinally) figure out #16,
