### ISSUE TITLE
[Meta] lyon 1.0

### ISSUE THREAD

**Issue by nical** [nical/lyon#53]
I would like to start thinking of what a 1.0 version should be like, what's missing and what planned features belong to a later 2.0 version.

The 1.0 version should be about selecting a set of key features and getting them to a point where:
 
- Their API is polished and stable (-ish)
- These features are fully implemented. For example some tessellators are currently missing or partially implemented (don't generate normals).

### Tessellators that work on flattened paths

 - `FillTessellator`.
   - [x] even-odd fill rule 
   - [ ] robust (fuzzed)
   - [ ] generate vertex normals
 - `StrokeTessellator`
   - [x] butt line caps
   - [x] square line caps
   - [ ] round line caps
   - [x] miter line joins
   - [x] miter clip line joins
   - [ ] round line joins
   - [ ] bevel line joins
 - All specific tessellators in `lyon_bezier::basic_shapes`.
   - [x] `fill_triangle`
   - [x] `stroke_triangle`
   - [x] `fill_quad`
   - [x] `stroke_quad`
   - [x] `fill_rectangle`
   - [x] `stroke_rectangle`
   - [x] `fill_rounded_rectangle`
   - [ ] `stroke_rounded_rectangle`
   - [x] `fill_circle`
   - [ ] `stroke_circle`
   - [ ] `fill_convex_polyline` (missing normals)
   - [x] `stroke_polyline`

For all of these, anything that requires flattening curves should consistently expose a tolerance threshold in its API rather than having a number of subdivisions or something alike.

`StrokeVertex` needs a new member that gives the advancement within a sub-path, and maybe the index of the sub-path and all of the stroke tessellators above need to support it.

### Other lyon crates

`lyon_path_builder` and `lyon_path_iterator` haven't changed a lot lately so we should give it a bit of polish on the API side of things but no outstanding new features are necessary. Lyon bezier has received more attention lately, it needs to receive a bit of API polish but extra features don't need to block 1.0.

## Lyon 2.0

In version 2.0, the focus will be to get all tessellators to handle quadratic bezier curve segments rather than just line segments. This is most likely going to be implemented in a new set of tessellators rather than modifying the existing ones.

## The high level renderer

This one is going to take a while to get right so it should probably be independent from the 1.0/2.0 schedule, or be part of 2.0 if it coincides.
