### ISSUE TITLE
lyon 0.17 TODO list

### ISSUE THREAD

**Issue by nical** [nical/lyon#566]
- [x] Fix error handling in the stroke tessellator.
 - [x] Avoid cloning paths when transforming them #575.
 - [x] Move some hidden symbols into `crate::private` module.
 - [x] Check that the builders and tessellators expose the right helpers. 
 - [x] implement `Winding::Negative` in `PathBuilder::add_rounded_rectangle` (#578).
 - [ ] Look for missing documentation.
 - [x] Decide whether `PathBuilder` methods should return endpoint IDs.
 - [x] Decide whether `PathBuilder::end` should take a boolean argument to close sub paths.
 - [x] Wait for next euclid version bump?
