### ISSUE TITLE
1.0 TODO

### ISSUE THREAD

**Issue by nical** [nical/lyon#698]
lyon_algorithms:

 - [x] Take `IntoIterator` instead of `Iterator` in public functions.
 - [x] Use `Box2D<f32>` instead of `Rect<f32>` and rename `bounding_rect` into `bounding_box`.
 - [x] Remove the path splitter? It's not very robust it should either be fixed or removed.
 - [ ]  Stroke-to-fill?
 - [ ] Dashing?

lyon_geom:

 - [x] Replace `BoundingRect` triat with `BoundingBox`.
 - [x]  Proper arc length implementation?
 - [ ] SIMD flattening?
 - [x] Should for_each_flattened's callback take a LineSegment instead of a Point? Used a lot s first check whether it affects perf.
 - [x] There are probably methods that could be added to the `Segment` trait (flattening for example).

lyon_tessellation:

 - [x] `EventQueue::into_builder` should take a tolerance parameter.
 - [x] `EventQueueBuilder::new` should take a tolerance parameter.
 - [x] Move `LineJoin`, `LineCap`, etc. in `lyon_path`? This would allow implementing stroke-to-fill without depending on `lyon_tessellation`.
 - [x] `Rename Side::Left`/`Right` into `Side::Positive/Negative` to avoid left/right handed confusion.
 - [ ] Maybe the `tessellate`/`tessellate_with_id` split could be simplified.
 - [x] Decide what to dow with triangle winding: Either add an extra parameter in the tessellators (slower, but nicer API) or add a parameter in `BuffersBuilder` and let people do it in `GeometryBuilder` (faster, less convenient).
 - [x] Fix stroking artifacts with cubic curve cusps.

lyon_path:
 - [x] Take custom attributes in the `PathBuilder` trait by default? 
 - [x] polish the path building API (try to avoid the attributes parameters where they aren't used).

lyon_extra:

 - [x] Remove the triangle rasterizer.
 - [ ] Use lyon's logo instead of the rust logo?
